<?php
$apiKey = "rzp_test_pfwyg1Z9ZgTfr4";
 ?>

 <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<form action="paymentsuccess.html" method="POST">
  <script
      src="https://checkout.razorpay.com/v1/checkout.js"
      data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
      data-amount="<?php echo $_POST['amount']*100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
      data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
      data-order_id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
      data-buttontext="Pay with Razorpay"
      data-name="Foodzilla"
      data-description="Food Ordering website"
      data-image="C:\Users\91917\OneDrive\Desktop\python\web development\html-personal site\tasty-food-chef-logo-mascot-template_190190-133.jpg"
      data-prefill.name="<?php echo $_POST['name'];?>"
      data-prefill.email="<?php echo $_POST['email'];?>"
      data-prefill.contact="<?php echo $_POST['mobile'];?>"
      data-theme.color="#0e99e4"
      ></script>
      <input type="hidden" custom="Hidden Element" name="hidden">
      </form>
